name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Connect AKS
        run: |
          az aks get-credentials \
            --resource-group rg-devops \
            --name aks-devops \
            --overwrite-existing

      - name: Deploy using Helm
        run: |
          helm upgrade --install node-app ./helm/node-app \
            --set image.tag=${{ github.sha }}